import { readFile } from "node:fs/promises";
import path from "node:path";
import type { DiagnosticReport } from "@/types/diagnostic.types";

export async function renderDiagnosticHtml(report: DiagnosticReport): Promise<string> {
  const templatePath = path.join(process.cwd(), "public", "diagnostico-estrategico-10x-template.html");
  let html = await readFile(templatePath, "utf8");
  const { answers, icpCard, opportunity, narratives } = report;
  const business = answers.step2?.businessName ?? "Tu negocio";
  const industry = answers.step2?.industry ?? "tu industria";
  const location = answers.step3_b2b?.geographyPriority ?? answers.step3_b2c?.geography ?? "México";
  const product = answers.step6?.productDescription ?? "tu oferta";
  const monthly = money(opportunity.totalMonthly);
  const annual = money(opportunity.totalAnnual);
  const additional = Math.max(1, Math.round(opportunity.additionalClientsMonthly));
  const score = icpCard.icpScore.total;

  html = html
    .replaceAll("Clínica Dental Sonrisa Plus", escapeHtml(business))
    .replaceAll("Clínica Sonrisa Plus", escapeHtml(business))
    .replaceAll("Sonrisa Plus", escapeHtml(business))
    .replaceAll("CDMX", escapeHtml(location))
    .replaceAll("Junio 2026", new Date(report.createdAt).toLocaleDateString("es-MX", { month: "long", year: "numeric" }))
    .replaceAll("ICP Score: 88/100", `ICP Score: ${score}/100`)
    .replaceAll("Dr. Roberto Castañeda · Propietario", escapeHtml(answers.step6?.ownerName ?? "Responsable de la cuenta"));

  html = replaceSection(html, "resumen", `<div class="sec-num">01 · Resumen Ejecutivo</div><h2 class="sec-title">Lo que entendemos<br>de tu negocio</h2><span class="method-ref">Diagnóstico Estratégico 10xTeam</span><div class="pull">&quot;${escapeHtml(narratives.executiveSummary)}&quot;</div><div class="g2"><div class="card gold"><p class="card-label cl-gold">El diagnóstico</p><p class="card-title">Lo que existe hoy</p><p class="card-body">${escapeHtml(icpCard.mainPain)}. La prioridad es construir un proceso que convierta interés en decisiones con seguimiento consistente.</p></div><div class="card teal"><p class="card-label cl-teal">La oportunidad</p><p class="card-title">Lo que es posible</p><p class="card-body">Con un sistema activo, el negocio puede capturar una oportunidad estimada de ${monthly} MXN mensuales y avanzar hacia ${escapeHtml(icpCard.promise)}.</p></div></div>`);
  html = replaceSection(html, "icp", `<div class="sec-num">02 · El Perfil ICP Completo</div><h2 class="sec-title">Las 5 capas del<br>cliente ideal</h2><p class="sec-sub">El perfil combina el contexto de compra, las objeciones y los canales que permiten hablar con precisión.</p><div class="layers">${layer("Situacional — El detonador", icpCard.trigger, [icpCard.trigger, icpCard.costOfInaction])}${layer("Descriptiva — Quién es", icpCard.profileDescription, [icpCard.primaryDecisionMaker, industry, location])}${layer("Psicográfica — Cómo piensa y siente", "El miedo y la aspiración que mueven la decisión.", [icpCard.topFear, icpCard.promise, icpCard.highRiskICP])}${layer("Conductual — Cómo compra y se comunica", "Canales y comportamiento de decisión.", [icpCard.channels.join(" · "), answers.step4?.salesCycleDuration ?? "Ciclo por definir"]) }${layer("Económica — El valor del intercambio", "El valor, autoridad y condiciones de inversión.", [icpCard.economicProfile.investmentRange, icpCard.economicProfile.budgetType, icpCard.economicProfile.decisionAuthority])}</div><div class="card red" style="margin-top:14px"><p class="card-label cl-red">Anti-ICP — a quién no escalar</p><p class="card-body">${escapeHtml(icpCard.antiICP)}</p></div>`);
  html = replaceSection(html, "persona", `<div class="sec-num">03 · El Buyer Persona</div><h2 class="sec-title">La persona,<br>no el perfil</h2><p class="sec-sub">Una lectura accionable de quién decide, qué teme y qué necesita escuchar.</p><div class="persona-card"><div class="persona-header"><div class="persona-avatar">${escapeHtml(narratives.buyerPersona.name.charAt(0) || "C")}</div><div><div class="persona-name">${escapeHtml(narratives.buyerPersona.name)}</div><div class="persona-role">${escapeHtml(narratives.buyerPersona.role)} · ${escapeHtml(location)}</div><div class="persona-tags"><span class="persona-tag">Perfil representativo</span><span class="persona-tag">${escapeHtml(industry)}</span><span class="persona-tag">Decisor relevante</span></div></div></div><div class="persona-body">${personaField("Un día en su vida", narratives.buyerPersona.dayInLife)}${personaField("Lo que piensa pero no dice", narratives.buyerPersona.unspokenThought)}${personaField("Lo que consume e influye", narratives.buyerPersona.influences)}${personaField("Su visión en 12 meses", narratives.buyerPersona.twelveMonthVision)}</div></div>`);
  html = replaceSection(html, "beliefs", `<div class="sec-num">04 · El Buyer Belief Map</div><h2 class="sec-title">Las creencias que<br>tu cliente necesita desarrollar</h2><p class="sec-sub">Cada creencia se conecta con un activo y una señal concreta de avance.</p><table class="belief-table"><thead><tr><th>#</th><th>Creencia a desarrollar</th><th>Material que la construye</th><th>Señal de que ocurrió</th></tr></thead><tbody>${narratives.beliefMap.map((item, index) => `<tr><td class="num">${String(index + 1).padStart(2, "0")}</td><td class="belief">${escapeHtml(item.belief)}</td><td>${escapeHtml(item.asset)}</td><td>${escapeHtml(item.signal)}</td></tr>`).join("")}</tbody></table>`);
  html = replaceSection(html, "mecanismo", `<div class="sec-num">07 · El Mecanismo Único</div><h2 class="sec-title">La razón específica<br>por la que funciona</h2><p class="sec-sub">El proceso que transforma intención en resultado con una ruta clara.</p><div class="mechanism"><p class="mechanism-label">El Mecanismo Único — ${escapeHtml(business)}</p><p class="mechanism-text">&quot;${escapeHtml(icpCard.uniqueMechanism)}&quot;</p><div class="mechanism-breakdown"><div class="mb-item"><p class="mb-label">Por qué fallan las alternativas</p><p class="mb-body">${escapeHtml(answers.step4?.whyCompetitorsFail ?? icpCard.previousSolutionsTried)}</p></div><div class="mb-item"><p class="mb-label">Qué hace diferente el proceso</p><p class="mb-body">${escapeHtml(icpCard.uniqueMechanism)}</p></div><div class="mb-item"><p class="mb-label">Resultado esperado</p><p class="mb-body">${escapeHtml(icpCard.promise)}</p></div></div></div>`);
  html = replaceSection(html, "oportunidad", `<div class="sec-num">08 · La Calculadora de Oportunidad</div><h2 class="sec-title">Lo que está<br>en juego cada mes</h2><p class="sec-sub">Calculado con los datos declarados por ${escapeHtml(business)}.</p><div class="calc"><div class="calc-header"><p class="calc-title">Resumen de Oportunidad</p><span class="calc-badge">Datos del negocio</span></div><div class="calc-body">${calcRow(`Ticket promedio de ${product}`, money(opportunity.ticketValue))}${calcRow("Prospectos perdidos estimados al mes", String(Math.round(opportunity.leadsLostMonthly)), "red")}${calcRow("Costo de tiempo mensual", monthly, "red")}${calcRow("Valor de prospectos perdidos", money(opportunity.lostLeadsValueMonthly), "red")}${calcRow("Costo de inacción anual", annual, "red")}${calcRow("Clientes adicionales estimados", `+${additional}`, "green")}${calcRow("Potencial mensual de crecimiento", money(opportunity.growthValueMonthly), "green")}</div><div class="calc-total"><div><p style="font-size:12px;color:var(--gold);margin-bottom:4px">Oportunidad mensual estimada</p><p style="font-size:12px;color:var(--muted)">Tiempo, fuga de leads y crecimiento potencial</p></div><p class="ct-val">${monthly}</p></div></div>`);
  html = replaceSection(html, "semana", `<div class="sec-num">05 · Tu Semana</div><h2 class="sec-title">Tu semana hoy<br>vs <em>tu semana con el sistema</em></h2><p class="sec-sub">La operación cambia al reducir tareas manuales y dar seguimiento consistente en ${escapeHtml(business)}.</p><table class="week-table"><thead><tr><th class="th-day">Día</th><th class="th-before">Tu negocio hoy</th><th class="th-after">Con 10xTeam</th></tr></thead><tbody>${["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"].map((day, index) => `<tr><td class="day">${day}</td><td class="before">${escapeHtml(weekBefore(index, icpCard.mainPain))}</td><td class="after">${escapeHtml(weekAfter(index, icpCard.promise, icpCard.uniqueMechanism))}</td></tr>`).join("")}</tbody></table><div class="week-total"><div class="wt-box before"><p class="wt-label">Tiempo invertido hoy</p><p class="wt-val">${escapeHtml(hoursLabel(answers.step6?.manualMarketingHours))}<span style="font-size:14px">/semana</span></p><p class="wt-sub">En tareas manuales de marketing y seguimiento</p></div><div class="wt-box after"><p class="wt-label">Tiempo con el sistema</p><p class="wt-val">~30 min<span style="font-size:14px">/semana</span></p><p class="wt-sub">Para revisar, aprobar y medir resultados</p></div></div>`);
  html = replaceSection(html, "trust", `<div class="sec-num">06 · El Trust Journey</div><h2 class="sec-title">El camino de interés<br>a decisión</h2><span class="method-ref">Ruta comercial basada en tu ICP y canales prioritarios</span><div class="journey">${[["La Creencia", narratives.beliefMap[0]?.belief], ["El Activo", narratives.beliefMap[0]?.asset], ["Distribución", icpCard.channels.join(" + ")], ["Captura", `Respuesta por ${answers.step5?.preferredContactMethod ?? "canal prioritario"}`], ["Nurture", `Seguimiento conectado a ${icpCard.mainPain}`], ["Scoring", "Interacción con materiales y señales de intención"], ["Handoff", `Conversación sobre ${icpCard.promise}`]].map(([name, description], index) => `<div class="j-step ${index === 1 || index === 3 ? "active" : ""}"><div class="j-num">PARTE ${index + 1}</div><div class="j-icon">${["&#127919;", "&#128203;", "&#128225;", "&#9995;", "&#128293;", "&#128202;", "&#129309;"][index]}</div><div class="j-name">${escapeHtml(name ?? "")}</div><div class="j-desc">${escapeHtml(description ?? "")}</div></div>`).join("")}</div><div class="card" style="margin-top:14px"><p class="card-label cl-gold">El Handoff correcto</p><div class="g2" style="margin-top:10px;gap:10px"><div style="background:rgba(220,38,38,.07);border:1px solid rgba(220,38,38,.2);border-radius:8px;padding:14px 16px"><p style="font-size:10px;font-family:'JetBrains Mono',monospace;color:#FCA5A5;margin-bottom:6px;text-transform:uppercase;letter-spacing:.08em">Handoff débil</p><p style="font-size:13px;font-style:italic;color:var(--text)">Hola, te escribo de ${escapeHtml(business)}. ¿Quieres conocer nuestra oferta?</p></div><div style="background:rgba(13,148,136,.07);border:1px solid rgba(13,148,136,.25);border-radius:8px;padding:14px 16px"><p style="font-size:10px;font-family:'JetBrains Mono',monospace;color:var(--teal-l);margin-bottom:6px;text-transform:uppercase;letter-spacing:.08em">Handoff poderoso</p><p style="font-size:13px;font-style:italic;color:var(--text)">Vimos que estás evaluando cómo resolver ${escapeHtml(icpCard.mainPain.toLowerCase())}. ¿Te explico en 10 minutos la ruta para ${escapeHtml(icpCard.promise.toLowerCase())}?</p></div></div></div>`);
  html = replaceSection(html, "contenido", `<div class="sec-num">10 · Estrategia de Contenido</div><h2 class="sec-title">Contenido que mueve<br>la decisión correcta</h2><p class="sec-sub">La estrategia acompaña al ICP desde el problema hasta la conversación de venta.</p><div class="lmf"><div class="lmf-seg" style="width:3%;background:#0EA5A0">3%</div><div class="lmf-seg" style="width:17%;background:#2563EB">17%</div><div class="lmf-seg" style="width:20%;background:#C9952A">20%</div><div class="lmf-seg" style="width:60%;background:#2A2E48">60%</div></div><div class="strategy-grid">${[["3% — Lista para actuar", "Captura de demanda", `Mensajes directos para quienes ya buscan ${icpCard.promise.toLowerCase()}.`], ["17% — Evaluando", "Consideración activa", narratives.beliefMap[1]?.asset], ["20% — Consciente del problema", "Activación", `Contenido que visibiliza ${icpCard.mainPain.toLowerCase()}.`], ["60% — No consciente", "Siembra de conciencia", narratives.beliefMap[0]?.asset]].map(([segment, title, body]) => `<div class="sg-item"><p class="sg-seg" style="color:var(--gold)">${escapeHtml(segment)}</p><p class="sg-title">${escapeHtml(title)}</p><p class="sg-body">${escapeHtml(body ?? "")}</p></div>`).join("")}</div>`);
  html = replaceSection(html, "materiales", `<div class="sec-num">11 · Materiales Generados</div><h2 class="sec-title">Tu kit completo de<br>materiales de crecimiento</h2><p class="sec-sub">Materiales alineados al ICP, mecanismo y canales seleccionados para ${escapeHtml(business)}.</p><div class="mat-grid">${[["&#129302;", "Bot de atención", `Responde con el contexto de ${icpCard.primaryDecisionMaker}`], ["&#128231;", "Secuencia de seguimiento", `Para avanzar hacia ${icpCard.promise}`], ["&#128172;", "Scripts de conversación", `Manejo de ${answers.step4?.topObjection ?? "objeciones"}`], ["&#128241;", "Contenido por canal", `Prioridad: ${icpCard.channels.join(", ")}`], ["&#128196;", "One-pager comercial", "Argumento, prueba y siguiente paso"], ["&#127919;", "Guion de objeciones", icpCard.uniqueMechanism]].map(([icon, name, description]) => `<div class="mat-card"><span class="mat-icon">${icon}</span><div><p class="mat-name">${escapeHtml(name)}</p><p class="mat-desc">${escapeHtml(description)}</p><span class="mat-lock ml-free">Activo al iniciar</span></div></div>`).join("")}</div>`);
  html = replaceSection(html, "roadmap", `<div class="sec-num">13 · El Roadmap de 12 Meses</div><h2 class="sec-title">Lo que es posible<br>con el sistema activo</h2><p class="sec-sub">Una ruta de activación progresiva, centrada en seguimiento, aprendizaje y mejora continua.</p><div class="roadmap">${[["Mes 1–2 · Activación", "Ordenar la base comercial", `Activar canales ${icpCard.channels.join(", ")}, respuesta rápida y una ruta para ${icpCard.promise.toLowerCase()}.`], ["Mes 3–6 · Optimización", "Aprender de señales reales", "Medir qué mensajes, activos y seguimientos generan conversaciones de calidad."], ["Mes 7–12 · Crecimiento compuesto", "Convertir aprendizaje en escala", `Con una oportunidad mensual estimada de ${monthly} MXN, iterar sobre los procesos que sostienen el crecimiento.`]].map(([period, title, description], index) => `<div class="rm-item"><div class="rm-left"><div class="rm-dot ${index === 0 ? "gold" : index === 1 ? "teal" : "blue"}"></div>${index < 2 ? '<div class="rm-line"></div>' : ""}</div><div><p class="rm-period">${escapeHtml(period)}</p><p class="rm-title">${escapeHtml(title)}</p><p style="font-size:12px;color:var(--muted);margin-bottom:10px;line-height:1.6">${escapeHtml(description)}</p><div class="rm-items"><span class="rm-tag">Seguimiento consistente</span><span class="rm-tag">ICP vivo</span><span class="rm-tag">Decisiones con datos</span></div></div></div>`).join("")}</div>`);
  html = replaceSection(html, "voz", `<div class="sec-num">12 · Así Suena tu Voz</div><h2 class="sec-title">No son plantillas.<br><em>Esto ya está escrito para ti.</em></h2><p class="sec-sub">Ejemplos construidos para el ICP de ${escapeHtml(business)}.</p><div class="voice-grid"><div class="voice-card"><div class="voice-head"><span class="voice-head-icon">&#129302;</span><span class="voice-head-label">Tu asistente · Primer mensaje</span></div><div class="voice-body"><div class="wa-mock"><div class="wa-bubble">${escapeHtml(narratives.voice.whatsapp)}<div class="wa-time">10:42</div></div></div></div></div><div class="voice-card"><div class="voice-head"><span class="voice-head-icon">&#128248;</span><span class="voice-head-label">Post · ${escapeHtml(icpCard.channels[0] ?? "Canal")}</span></div><div class="voice-body"><div class="ig-mock"><div class="ig-img">${escapeHtml(narratives.voice.instagramHook)}</div><div class="ig-caption">${escapeHtml(narratives.voice.instagramCaption)}</div></div></div></div><div class="voice-card"><div class="voice-head"><span class="voice-head-icon">&#9993;</span><span class="voice-head-label">Email · Primer toque</span></div><div class="voice-body"><div class="email-mock"><div class="email-head"><p class="email-subject">${escapeHtml(narratives.voice.emailSubject)}</p></div><div class="email-body">${paragraphs(narratives.voice.emailBody)}</div></div></div></div><div class="voice-card"><div class="voice-head"><span class="voice-head-icon">&#127916;</span><span class="voice-head-label">Guión de Reel · 30 seg</span></div><div class="voice-body" style="font-size:12px;line-height:1.8;color:var(--text)"><p>${escapeHtml(narratives.voice.reelScript)}</p></div></div></div>`);

  return html
    .replaceAll("$11.2<span>M</span>", `${annual}<span> MXN</span>`)
    .replaceAll("+38<span>%</span>", `+${additional}<span></span>`)
    .replaceAll("costo por paciente baja", "costo por cliente baja")
    .replaceAll("atender a los pacientes que ya llegaron listos", "atender a los clientes que ya llegaron listos");
}

function replaceSection(html: string, id: string, content: string): string {
  const expression = new RegExp(`(<section class="sec" id="${id}">)[\\s\\S]*?(</section>)`);
  return html.replace(expression, `$1${content}$2`);
}

function layer(name: string, description: string, tags: string[]): string {
  return `<div class="layer"><div class="layer-num">•</div><div class="layer-content"><div class="layer-name">${escapeHtml(name)}</div><div class="layer-body">${escapeHtml(description)}</div><div class="layer-tags">${tags.filter(Boolean).map((tag) => `<span class="ltag">${escapeHtml(tag)}</span>`).join("")}</div></div></div>`;
}

function personaField(label: string, value: string): string {
  return `<div><p class="pf-label">${escapeHtml(label)}</p><p class="pf-text">${escapeHtml(value)}</p></div>`;
}

function calcRow(label: string, value: string, className = ""): string {
  return `<div class="calc-row"><span class="calc-label">${escapeHtml(label)}</span><span class="calc-val ${className}">${escapeHtml(value)} <span class="calc-note">MXN</span></span></div>`;
}

function paragraphs(value: string): string {
  return escapeHtml(value).split(/\n+/).map((paragraph) => `<p>${paragraph}</p>`).join("");
}

function money(value: number): string {
  return `$${Math.round(value).toLocaleString("es-MX")}`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] as string);
}

function hoursLabel(value: DiagnosticReport["answers"]["step6"] extends infer Step6 ? Step6 extends { manualMarketingHours: infer Hours } ? Hours | undefined : undefined : undefined): string {
  const labels: Record<string, string> = { less_2hrs: "<2 hrs", "2_5hrs": "2–5 hrs", "5_10hrs": "5–10 hrs", more_10hrs: "+10 hrs" };
  return labels[value as string] ?? "2–5 hrs";
}

function weekBefore(index: number, pain: string): string {
  return [
    `El equipo atiende solicitudes según disponibilidad y ${pain.toLowerCase()}.`,
    "La creación de contenido depende de encontrar tiempo entre la operación.",
    "Las conversaciones que no avanzan quedan sin una siguiente acción definida.",
    "Las tareas de seguimiento se reparten entre herramientas sin una vista única.",
    "La objeción se responde de forma distinta según quién atiende.",
  ][index] ?? pain;
}

function weekAfter(index: number, outcome: string, mechanism: string): string {
  return [
    `El sistema organiza prioridades y acelera las primeras respuestas hacia ${outcome.toLowerCase()}.`,
    "Los mensajes y piezas de contenido parten de una misma lectura del ICP.",
    "Los prospectos reciben seguimiento basado en su etapa e interés mostrado.",
    `${mechanism} conecta conversación, contenido y el siguiente paso comercial.`,
    "El equipo usa un guion coherente para avanzar objeciones sin improvisar.",
  ][index] ?? outcome;
}